# /// script
# requires-python = "==3.13.*"
# dependencies = ["fonttools==4.63.0", "brotli==1.1.0"]
# ///
"""Regenerate the on-demand Yozai font subsets."""

from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from tempfile import mkdtemp

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/assets/fonts.woff2"
OUTPUT = ROOT / "src/assets/fonts"


def unicode_ranges(codepoints):
    ranges = []
    start = end = codepoints[0]
    for codepoint in codepoints[1:]:
        if codepoint == end + 1:
            end = codepoint
        else:
            ranges.append(f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}")
            start = end = codepoint
    ranges.append(f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}")
    return ", ".join(ranges)


def write_subset(item):
    name, codepoints, source = item
    font = TTFont(source, recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.name_legacy = True
    options.notdef_outline = True
    # Keep the OpenType ligature/vertical features; FontTools cannot subset
    # the equivalent Apple shaping tables without leaving stale glyph IDs.
    options.drop_tables += ["feat", "morx"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    # FontTools may also keep a mirrored character needed for bidirectional text.
    missing = set(codepoints) - set(font.getBestCmap())
    if missing:
        raise ValueError(f"Characters missing from {name}: {sorted(missing)}")
    font.flavor = "woff2"
    path = OUTPUT / name
    font.save(path)
    font.close()
    return name, codepoints, path.stat().st_size


def main():
    # Reconstruct the WOFF2 glyph stream once, not once per subset.
    decoded = Path(mkdtemp(prefix="aassistant-font-source-", dir="/tmp")) / "source.ttf"
    print("Decoding source font...", flush=True)
    with TTFont(SOURCE, recalcTimestamp=False) as font:
        available = set(font.getBestCmap())
        font.flavor = None
        font.save(decoded)
    print(f"Decoded source: {decoded}", flush=True)

    # Put interface text and common Latin/combining/punctuation characters in
    # one small request. Everything else remains available in bounded chunks.
    common = set(range(0x250))
    common.update(range(0x300, 0x370))
    common.update(range(0x2000, 0x2070))
    common.update(range(0x3000, 0x3040))
    for path in (ROOT / "src").rglob("*"):
        if path.suffix in {".svelte", ".ts"}:
            common.update(map(ord, path.read_text(encoding="utf-8")))
    common &= available
    remaining = sorted(available - common)
    chunks = [("yozai-common.woff2", sorted(common), decoded)]
    chunks.extend(
        (f"yozai-{index // 256:03d}.woff2", remaining[index:index + 256], decoded)
        for index in range(0, len(remaining), 256)
    )
    OUTPUT.mkdir(parents=True, exist_ok=True)
    rules = ["/* Generated by pnpm fonts:split. */\n"]
    total_bytes = 0
    with ProcessPoolExecutor(max_workers=4) as pool:
        for index, (name, codepoints, size) in enumerate(pool.map(write_subset, chunks), 1):
            total_bytes += size
            rules.append(
                "@font-face {\n"
                "  font-family: 'Yozai Font';\n"
                f"  src: url('./{name}') format('woff2');\n"
                "  font-weight: 400;\n"
                "  font-style: normal;\n"
                "  font-display: swap;\n"
                f"  unicode-range: {unicode_ranges(codepoints)};\n"
                "}\n"
            )
            if index == 1 or index % 10 == 0 or index == len(chunks):
                print(f"{index}/{len(chunks)} subsets: {name} ({size:,} bytes)", flush=True)
    (OUTPUT / "yozai.css").write_text("\n".join(rules), encoding="utf-8")
    print(f"Preserved {len(available):,} codepoints; all subsets total {total_bytes:,} bytes.")


if __name__ == "__main__":
    main()
